---
title: snomnom.com - Eating, Traveling, and Cooking
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: stefanomnom@gmail.com
description: 'Eating, Traveling, Cooking - mixed with the occasional joke and all.
  Check it out!

'
permalink: ":title/"
baseurl: "/"
url: http://snomnom.com
site-name: snomnom.com
sub-title: Eating, Traveling, Cooking, and more
author: Stefan Hermanek
author-pic: stefan_header.jpg
about-author: Hi, I'm Stefan. By day, I'm a Senior Product Manager at People.ai. In
  my spare time I enjoy food, travel, and photography.
website: snomnom.com
twitter: "@stefanhermanek"
instagram: iamstefanh
mailchimp: "//snomnom.us4.list-manage.com/subscribe/post?u=9c536787f3a0d290b3aba695a&amp;id=f010a161b6"
discus_identifier: mr-brown
analytics: UA-155022564-1
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
include:
- _pages
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
- package-lock.json
- assets/css/sass/
