title: Eating, Traveling, and Cooking - snomnom.com
email: hermanek.stefan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eating, Traveling, Cooking - mixed with the occasional joke and all. Check it out!
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://snomnom.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Stefan Hermanek # add your name
author-pic: stefan_header.jpg
about-author: Hi, I'm Stefan. By day, I'm a Senior Product Manager at People.ai. In my spare time I enjoy food, travel, and photography.

# Contact links
email: 'stefanomnom@gmail.com' #
# phone: # Add your Phone number
website: 'snomnom.com' # Add your website, do not add http://
# linkedin: # Add your Linkedin handle
# github: # 'sjhermanek' # Add your Github handle
twitter: '@stefanhermanek' # Add your Twitter handle
# facebook: # Add your Facebook handle
instagram: 'iamstefanh' # Add your Instagram handle
# pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
